name: reusable
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      TOK:
        required: false
jobs:
  r:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        shell: bash
        run: echo "tag=${{ inputs.tag }}"
